import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateBackofficeManagedTables1773273600000
  implements MigrationInterface
{
  name = 'CreateBackofficeManagedTables1773273600000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE EXTENSION IF NOT EXISTS "pgcrypto"
    `);

    await queryRunner.query(`
      DO $$
      BEGIN
        IF EXISTS (
          SELECT 1
          FROM information_schema.tables
          WHERE table_schema = 'public'
            AND table_name = 'questions'
        ) AND NOT EXISTS (
          SELECT 1
          FROM information_schema.tables
          WHERE table_schema = 'public'
            AND table_name = 'common_questions'
        ) THEN
          ALTER TABLE "questions" RENAME TO "common_questions";
        END IF;
      END
      $$;
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "common_questions" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "content" text NOT NULL,
        "status" varchar(255) NOT NULL DEFAULT 'ACTIVE',
        "created_at" timestamp NOT NULL DEFAULT NOW(),
        "updated_at" timestamp NOT NULL DEFAULT NOW(),
        "deleted_at" timestamp NULL
      )
    `);

    await queryRunner.query(`
      ALTER TABLE "common_questions"
      ADD COLUMN IF NOT EXISTS "deleted_at" timestamp NULL
    `);

    await queryRunner.query(`
      SELECT setval(
        pg_get_serial_sequence('common_questions', 'id'),
        COALESCE((SELECT MAX(id) FROM common_questions), 1),
        true
      )
    `);

    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "idx_common_questions_status_created_at"
        ON "common_questions" ("status", "created_at" DESC)
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "notices" (
        "id" bigserial PRIMARY KEY,
        "title" varchar NOT NULL,
        "content" text NOT NULL,
        "category" varchar(30) NOT NULL DEFAULT 'NOTICE',
        "status" varchar(20) NOT NULL DEFAULT 'ACTIVE',
        "created_at" timestamp NOT NULL DEFAULT NOW(),
        "updated_at" timestamp NOT NULL DEFAULT NOW()
      )
    `);

    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "idx_notices_status_created_at"
        ON "notices" ("status", "created_at" DESC)
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "notice_images" (
        "id" bigserial PRIMARY KEY,
        "notice_id" bigint NOT NULL,
        "image_url" varchar NOT NULL,
        "sort_order" int NOT NULL DEFAULT 0,
        CONSTRAINT "fk_notice_images_notice_id"
          FOREIGN KEY ("notice_id") REFERENCES "notices"("id")
          ON DELETE CASCADE
      )
    `);

    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "idx_notice_images_notice_id_sort_order"
        ON "notice_images" ("notice_id", "sort_order" ASC)
    `);

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "sanctions" (
        "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        "type" varchar(20) NOT NULL,
        "reason" text NULL,
        "created_at" timestamp NOT NULL DEFAULT NOW(),
        "user_id" bigint NOT NULL
      )
    `);

    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "idx_sanctions_user_id_created_at"
        ON "sanctions" ("user_id", "created_at" DESC)
    `);

    await queryRunner.query(`
      DO $$
      BEGIN
        IF EXISTS (
          SELECT 1
          FROM information_schema.tables
          WHERE table_schema = 'public'
            AND table_name = 'users'
        ) AND NOT EXISTS (
          SELECT 1
          FROM information_schema.table_constraints
          WHERE table_schema = 'public'
            AND table_name = 'sanctions'
            AND constraint_name = 'fk_sanctions_user_id'
        ) THEN
          ALTER TABLE "sanctions"
            ADD CONSTRAINT "fk_sanctions_user_id"
            FOREIGN KEY ("user_id") REFERENCES "users"("id")
            ON DELETE CASCADE;
        END IF;
      END
      $$;
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP TABLE IF EXISTS "notice_images"
    `);
    await queryRunner.query(`
      DROP TABLE IF EXISTS "sanctions"
    `);
    await queryRunner.query(`
      DROP TABLE IF EXISTS "notices"
    `);
    await queryRunner.query(`
      DROP TABLE IF EXISTS "common_questions"
    `);
  }
}
