\getenv DEV_DB_NAME DEV_DB_NAME
\getenv SPRING_DB_USER SPRING_DB_USER
\getenv SPRING_DB_PASSWORD SPRING_DB_PASSWORD
\getenv BACKOFFICE_DB_USER BACKOFFICE_DB_USER
\getenv BACKOFFICE_DB_PASSWORD BACKOFFICE_DB_PASSWORD

\set ON_ERROR_STOP on

DO
$$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'SPRING_DB_USER') THEN
    EXECUTE format(
      'CREATE ROLE %I LOGIN PASSWORD %L',
      :'SPRING_DB_USER',
      :'SPRING_DB_PASSWORD'
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'BACKOFFICE_DB_USER') THEN
    EXECUTE format(
      'CREATE ROLE %I LOGIN PASSWORD %L',
      :'BACKOFFICE_DB_USER',
      :'BACKOFFICE_DB_PASSWORD'
    );
  END IF;
END
$$;

SELECT format('CREATE DATABASE %I', :'DEV_DB_NAME')
WHERE NOT EXISTS (
  SELECT 1 FROM pg_database WHERE datname = :'DEV_DB_NAME'
)
\gexec

SELECT format('GRANT CONNECT ON DATABASE %I TO %I', :'DEV_DB_NAME', :'SPRING_DB_USER')
\gexec
SELECT format('GRANT CONNECT ON DATABASE %I TO %I', :'DEV_DB_NAME', :'BACKOFFICE_DB_USER')
\gexec

\connect :DEV_DB_NAME

GRANT USAGE, CREATE ON SCHEMA public TO :SPRING_DB_USER;
GRANT USAGE, CREATE ON SCHEMA public TO :BACKOFFICE_DB_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :SPRING_DB_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :BACKOFFICE_DB_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO :SPRING_DB_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO :BACKOFFICE_DB_USER;
